[package]
name = "hs-mannheim-informatik-thesis-template"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Christian Leingang @christian-leingang", "Tim Jensen <@tjensen42>"]
license = "MIT"
description = "Unofficial Template for a bachelor or master thesis in typst."
repository = "https://github.com/tjensen42/HSMA-typst-template"
keywords = ["hsma", "thesis"]
categories = ["thesis", "report"]
exclude = []

[template]
path = "template"
entrypoint = "main.typ"
# thumbnail = "thumbnail.png"
